#!/usr/bin/env bash
# This script installs the nginx web server and serve a page containing 'Hello World!
sudo apt-get update -y
sudo apt-get install nginx -y
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
