#!/usr/bin/env bash
# This script install nginx on the server and server an html file
sudo apt-get update -y
sudo apt-get install nginx -y
sudo su
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
