#!/usr/bin/env bash
# This script configure the nginx server to redirect any user that
# visits '/redirect_me' to youtube.com

# Update the server
sudo apt-get update -y

# Install the nginx web server
sudo apt-get install nginx -y

sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
