#!/usr/bin/env bash
# This script configured nginx to serve a custom 404 error page
# when the user visits a page not located on the server

# Update the server
sudo apt-get update -y

# Install nginx
sudo apt-get install nginx -y

# Pipe the hello world string to '/var/www/html/index.html'
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

# Edit the '/etc/nginx/sites-available/default' in place
# Search for the position of 'listen 80 default_server' in the specified file
# and append 'rewrite ^/redirect_me https://www.youtube.com/@muslimsage/ permanent;' at the end
sed -i "46i rewrite ^/redirect_me https://www.youtube.com/@muslimsage permanent;" /etc/nginx/sites-available/default

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null

# Register the new 404 page
sed -i "46i error_page 404 /custom_404.html;" /etc/nginx/sites-available/default

# Start the nginx server
service nginx restart
