#!/usr/bin/env bash
# Install and configure HAproxy load balancer

# Update and upgrade the packages
apt-get update
apt-get upgrade -y

# Add HAProxy PPA to the packages repo
apt-get install software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.8 -y
apt-get update

# Install haproxy
apt-get install haproxy -y
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "
	frontend haproxy_balancer
		bind *:80
		mode http
		default_backend webservers

	backend webservers
		balance roundrobbin
		server 374236-web-01 54.160.88.197 check
		server 374236-web-02 52.91.178.63 check
" >> /etc/haproxy/haproxy.cfg

service haproxy restart
