#!/usr/bin/env bash
# Display 'Best School' and then on the ninth iteration, displays 'Hi'
i=0
while [ $i -lt 20 ]
do
	echo $(( i + 1 ))
	case $i in
		3) echo "bad luck from China";;
		8) echo "bad luck from Japan";;
		16) echo "bad luck from Italy";;
	esac
	(( i++ ))
done 
