#!/usr/bin/env bash
# Checking if a file exist or not
file="school"
if [ -e "$file" ]
then
	echo "school file exists"
	if [ "$(wc -l < "$file")" -eq 0 ]
	then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi

	if [ -f "$file" ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
